apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: event-message-parsing
  annotations: # human-readable info
    author: jduckett
    org: NASIC/GSPO
    email: jduckett@awetomaton.com
    description: |
      This resource contains a variety of commonly-used parsing templates.

  labels: # Used for querying / subsetting templates
    class: parsing
    source: event-notifications

spec: # https://argoproj.github.io/argo-workflows/fields/#workflowspec
  templates:
#------------------------------------------------------------------------------------------------------------------------------
  - name: parse-s3-sns
    # Currently extracts bucket and path of the file, could be expanded to return additional message params.
    metadata:
      annotations: # human-readable info
        author: jduckett
        org: NASIC/GSPO
        email: jduckett@awetomaton.com
        description: |
          This template parses an AWS SNS message and maps them to output parameters.
      labels:
        class: parsing
        source: sns

    # TODO: Fill metrics in. Default workflow template should define global metrics to collect for all workflows.
    # metrics:

    inputs:
      parameters:
      - name: sns-message
        description: SNS message of s3 activity.
      artifacts:
      - name: message
        path: sns-message.json
        raw:
          data: |
            {{inputs.parameters.sns-message}}

    container:
      image: stedolan/jq
      command: [sh, -c]
      args: [" jq '.Message | fromjson | .Records[0].s3.object.key' sns-message.json > s3-path.txt |\
        jq '.Message | fromjson | .Records[0].s3.bucket.name' sns-message.json > s3-bucket.txt"]

    outputs:
      parameters:
        - name: s3-path
          description: Path of s3 object that triggered the notification.
          valueFrom:
            path: s3-path.txt
        - name: s3-bucket
          description: Bucket that the s3 object derived from.
          valueFrom:
            path: s3-bucket.txt
#------------------------------------------------------------------------------------------------------------------------------
  - name: parse-minio
    # Currently extracts bucket and path of the file, could be expanded to return additional message params.
    metadata:
      annotations: # human-readable info
        author: jduckett
        org: NASIC/GSPO
        email: jduckett@awetomaton.com
        description: |
          This template parses a MinIO message and maps them to output parameters.
      labels:
        class: parsing
        source: minio

    # TODO: Fill metrics in. Default workflow template should define global metrics to collect for all workflows.
    # metrics:

    inputs:
      parameters:
      - name: minio-message
        description: MinIO message of file activity.
      artifacts:
      - name: message
        path: minio-message.json
        raw:
          data: |
            {{inputs.parameters.minio-message}}

    container:
      image: stedolan/jq
      command: [sh, -c]
      args: [" jq '.notification[0].s3.object.key' minio-message.json > minio-path.txt |\
        jq '.notification[0].s3.bucket.name' minio-message.json > minio-bucket.txt"]

    outputs:
      parameters:
        - name: minio-path
          description: Path of minio object that triggered the notification.
          valueFrom:
            path: minio-path.txt
        - name: minio-bucket
          description: Bucket that the minio object derived from.
          valueFrom:
            path: minio-bucket.txt