apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: minio-examples
spec:
  templates:
  - name: log-demo
    # Currently extracts bucket and path of the file, could be expanded to return additional message params.
    metadata:
      annotations: # human-readable info
        author: jduckett
        org: NASIC/GSPO
        email: jduckett@awetomaton.com
        description: |
          This template passes a string to whalesay.
      labels:
        class: processing

    inputs:
      parameters:
      - name: string-value
        description: Input message.

    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.string-value}}"]

#-----------------------------------------

  - name: artifact-demo
    # Currently extracts bucket and path of the file, could be expanded to return additional message params.
    metadata:
      annotations: # human-readable info
        author: jduckett
        org: NASIC/GSPO
        email: jduckett@awetomaton.com
        description: |
          This template passes a string to whalesay and logs an artifact.
      labels:
        class: processing

    inputs:
      parameters:
      - name: string-value
        description: Input message.

    container:
      image: docker/whalesay
      command: [sh, -c]
      args: ["cowsay {{inputs.parameters.string-value}} | tee /tmp/hello_world.txt"]

    outputs:
      artifacts:
      # generate hello-art artifact from /tmp/hello_world.txt
      # artifacts can be directories as well as files
      - name: hello-art
        path: /tmp/hello_world.txt
        s3:
          endpoint: argo-artifacts:9000
          bucket: algnext-dev-output
          key: output/demo2/hello_world.txt.tgz
          insecure: true
          accessKeySecret:
            name: minio-secret
            key: accesskey
          secretKeySecret:
            name: minio-secret
            key: secretkey
        archive:
          none: {}