# WARNING - the file CANNOT have a newline after secretkey / at the end of the file. Secrets will not work if there is a newline.
# https://github.com/argoproj/argo-workflows/issues/726

apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  accesskey: <Base64-encoded accesskey>
  secretkey: <Base64-encoded secretkey>