apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: kafka-sensor-filtered
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    #- name: test-dep
    #  eventSourceName: kafka
    #  eventName: example
    - name: test-dep-filtered
      eventSourceName: kafka
      eventName: example
      filters:
        data:
          - path: body.cust_id
            type: number
            comparator: ">"
            value:
              - "3" 
  triggers:
    - template:
        name: kafka-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: kafka-workflow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # this is the value that should be overridden
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.cust_id
              dest: spec.arguments.parameters.0.value
