apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sns
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: aws-sns
      eventName: example
  triggers:
    - template:
        name: sns-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: aws-sns-worfklow-
              spec:
                entrypoint: main
                arguments:
                  parameters:
                  - name: message
                templates:
                - name: main
                  dag:
                    tasks:
                    - name: extract-message
                      templateRef:
                        name: event-message-parsing
                        template: parse-s3-sns
                      arguments:
                        parameters:
                          - name: sns-message
                            value: "{{workflow.parameters.message}}"

                    - name: artifact-test
                      dependencies: [extract-message]
                      templateRef:
                        name: workflow-input-artifact-template
                        template: whalesay
                      arguments:
                        parameters:
                          - name: message
                            value: "{{tasks.extract-message.outputs.parameters.s3-path}}"
                            
                    - name: whalesay
                      dependencies: [extract-message]
                      template: whalesay
                      arguments:
                        parameters:
                        - name: message
                          value: "{{tasks.extract-message.outputs.parameters.s3-path}}"

                # - name: parse-s3-sns
                #   inputs:
                #     parameters:
                #     - name: sns-message
                #     artifacts:
                #     - name: message
                #       path: sns-message.json
                #       raw:
                #         data: |
                #           {{inputs.parameters.sns-message}}

                #   container:
                #     image: stedolan/jq
                #     command: [sh, -c]
                #     args: [" jq '.Message | fromjson | .Records[0].s3.object.key' sns-message.json > s3-path.txt |\
                #      jq '.Message | fromjson | .Records[0].s3.bucket.name' sns-message.json > s3-bucket.txt"]

                #   outputs:
                #     parameters:
                #       - name: s3-path
                #         valueFrom:
                #           path: s3-path.txt
                #       - name: s3-bucket
                #         valueFrom:
                #           path: s3-bucket.txt

          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value